/* The vocabulary the page is written in, for a reader who has the basics of a TLE and not much more. Each entry has an id, so a
 * note elsewhere can point at the term it leans on (the Professor's notes link to #t-sso, #t-ltan and the rest: a note that
 * names a term must find it here).
 *
 * Moved from the markup of #sec-terms in legacy/index.html (main@4eadd7a), lines 1769-1888, as data: the 28 terms, their ids,
 * and every word of their text. */
export interface Term { id: string; term: string; text: string }

export const GLOSSARY: readonly Term[] = [
  { id: "t-aos", term: "AOS, LOS",
    text: "Acquisition and loss of signal: the instants a pass rises through the elevation mask and sets back through it. Here they are geometric crossings of 5°, found to the millisecond, not a radio event. A time marked * is the edge of the window instead, for a pass already up when it opens or still up when it closes." },
  { id: "t-el", term: "Elevation (el), azimuth, mask",
    text: "Elevation is the angle above the observer's horizon; azimuth the compass bearing, from north through east. The mask is the elevation a pass must clear to count, 5° here, standing in for terrain and buildings. The highest point of a pass is its culmination." },
  { id: "t-z", term: "Z, UTC, UTC+7",
    text: "Z after a time means UTC, which every figure is computed in. UTC+7 is the observer's local time, Bangkok's unless another site is chosen; the window-start field is read and written in it. Dates without a year are month-day: 09-26 is 26 September." },
  { id: "t-circle", term: "Access circle, footprint",
    text: "The access circle is centred on the observer: a spacecraft at the window's mean altitude is above the mask while the point beneath it is inside the circle. The footprint is centred beneath the spacecraft: the ground it can be seen from above the mask at that moment." },
  { id: "t-window", term: "Window, sim time",
    text: "The span the analysis covers, 24 h from now unless moved. The clock that drives the globe, the map and the countdown can be scrubbed or sped up; \"sim time\" beside a readout means it is not showing the present." },
  { id: "t-ids", term: "NORAD ID, COSPAR ID",
    text: "Two catalogue numbers for one object. The NORAD number is the US Space Force's sequential catalogue number. The COSPAR ID, or international designator, is the launch year, the launch's number in that year and a letter code for the piece." },
  { id: "t-tle", term: "TLE, element set, epoch",
    text: "A two-line element set: an orbit published as SGP4 mean elements in fixed columns of text. Its epoch is the instant the elements describe; predictions are best near it and drift with distance from it, which is what the age chip in the header is counting." },
  { id: "t-sgp4", term: "SGP4, SDP4",
    text: "Simplified General Perturbations 4, the analytic propagator TLEs are fitted to and the only one they are meaningful with. SDP4 is its deep-space branch, which takes over for periods of 225 min or more. When SGP4 finds an orbit has decayed into the Earth it stops with error 6." },
  { id: "t-mean", term: "Mean and osculating elements",
    text: "Mean elements, a TLE's, have SGP4's periodic terms averaged out and mean something only inside SGP4. Osculating elements are the two-body orbit through the actual position and velocity at one instant. Kozai and Brouwer are two conventions for the mean motion; a TLE carries Kozai's." },
  { id: "t-frames", term: "TEME, ECI, ♈︎",
    text: "ECI is any Earth-centred inertial frame, whose axes are fixed against the stars rather than turning with the Earth. The globe's puts its x axis on the First Point of Aries, ♈︎: the direction of the Sun at the March equinox, which right ascensions are measured from. TEME, true equator and mean equinox, is the one SGP4 works in." },
  { id: "t-angles", term: "Ω, i, ω, M, θ or ν",
    text: "RAAN, the right ascension of the ascending node: the angle east from ♈︎ to where the orbit crosses the equator going north (☊). Inclination, the tilt of the orbit plane to the equator. Argument of perigee, from the node to perigee within the plane. Mean anomaly, the phase an evenly moving point would have; true anomaly, the actual angle from perigee, θ on the globe and ν in the tables." },
  { id: "t-vectors", term: "h, e, v on the globe",
    text: "h is the specific angular momentum r × v, normal to the orbit plane, in km²/s. e is the eccentricity vector, which points at perigee and is as long as the eccentricity. v is the velocity; vt is its transverse part, at right angles to the radius, and vn its radial part." },
  { id: "t-period", term: "Nodal and Kepler period",
    text: "The nodal period is measured, from one ascending node to the next. The Kepler period is 2π√(a³/μ) from the semi-major axis. The page shows the nodal one, except where the node is too poorly defined to time, as for a near-equatorial geostationary orbit." },
  { id: "t-bstar", term: "B*, 1/ER",
    text: "SGP4's drag term. Its unit is the inverse Earth radius, 1/ER. It is fitted along with the elements and soaks up whatever else the fit could not model, so it is not a measured area-to-mass ratio. Here you type the area-to-mass ratio A/m instead, in m²/kg, with Cd = 2.2; B* is then worked out from it for the height typed, so that SGP4 decays at the rate this page’s Decay model gives, and it is a guess, not a measurement." },
  { id: "t-mag", term: "Magnitude, std mag, phase",
    text: "Astronomical brightness, where smaller is brighter and 5 magnitudes is a factor of 100. About +6 is the faintest the naked eye sees in a dark sky, and the page's threshold. The standard magnitude is an object's brightness at 1,000 km with half its face lit; the estimate scales it by the range and by the phase angle, at the spacecraft between the observer and the Sun." },
  { id: "t-shadow", term: "Umbra, penumbra",
    text: "Earth's shadow, where the Sun is wholly hidden, and the fringe around it where it is partly hidden. The naked-eye verdict counts only moments in full sunlight; penumbral ones are reported on their own." },
  { id: "t-pov", term: "POV, FOV, GSD",
    text: "Point of view: the camera that rides the spacecraft, looking along its track. Field of view: the width of that lens, in degrees. Ground sample distance: the ground one screen pixel covers." },
  { id: "t-ar", term: "AR, heading, declination",
    text: "Augmented reality: on a phone or tablet, the sky drawn over the rear camera’s picture where the phone points — the spacecraft, its pass, the horizon, the 5° mask and the Sun. The heading is the bearing the camera faces, from true north through east. A phone’s compass finds magnetic north; the declination is how far that lies east (+) or west (−) of true north at the observer, taken from the World Magnetic Model, WMM2025. A phone’s compass is often several degrees out, so the drawn sky can be turned by hand." },
  { id: "t-reentry", term: "Decay, entry interface",
    text: "Decay is the slow loss of altitude to atmospheric drag. The entry interface, taken as 120 km, is the height below which an orbit lasts a revolution or two at most; an object SGP4 takes below it has re-entered or is about to." },
  { id: "t-brief", term: "Earth Resources group, the brief",
    text: "CelesTrak's list of Earth-observation spacecraft. The assignment asks for a spacecraft from it; KNACKSAT-2, the default here, is not in it." },
  { id: "t-wgs", term: "WGS-72, WGS-84, R⊕",
    text: "Two editions of the World Geodetic System's model of the Earth. SGP4 is defined on WGS-72; latitudes and altitudes here are geodetic on WGS-84. R⊕ is the equatorial radius, 6378.137 km." },
  { id: "t-sso", term: "Sun-synchronous",
    text: "An orbit whose plane turns about 0.986 degrees a day, the rate the Sun appears to move through the stars, so it keeps the same angle to the Sun all year and crosses the equator at the same local solar time every day. The Earth's equatorial bulge does the turning, and it only matches for a retrograde tilt a little over 90 degrees (97.4 at 500 km), up to about 5,970 km high." },
  { id: "t-ltan", term: "LTAN, LTDN",
    text: "Local time of the ascending node: the local mean solar time at which the satellite crosses the equator northbound; LTDN is the southbound crossing, twelve hours away. A sun-synchronous orbit keeps both fixed. 10:30 is a common choice for imaging; 06:00 or 18:00 is a dawn-dusk orbit." },
  { id: "t-beta", term: "Beta angle, eclipse",
    text: "The angle between the Sun's direction and the orbit plane. At 0 the Sun lies in the plane and the satellite spends longest in Earth's shadow; beyond a limit set by the height (the arcsine of the Earth's radius over the orbit radius, 68 degrees at 500 km) the shadow misses the orbit and there is no eclipse. Beta changes over the year as the plane and the Sun move. The eclipse figures use a cylindrical shadow and ignore the penumbra." },
  { id: "t-geo", term: "Geostationary, geosynchronous",
    text: "A period of one sidereal day, 23 h 56 min 4 s, which takes 35,786 km. Geosynchronous means only the period; geostationary adds no tilt and no eccentricity, so the satellite stays over one point of the equator. A tilted one traces a figure-eight about it each day." },
  { id: "t-crit", term: "Critical inclination",
    text: "63.4 degrees (and 116.6), where the Earth's bulge stops turning an orbit's perigee. Orbits that depend on where their apogee sits, Molniya and Tundra, use it." },
  { id: "t-belts", term: "Van Allen belts",
    text: "Two doughnuts of charged particles trapped by the Earth's magnetic field: an inner one, mostly protons, between about 1,000 and 6,000 km, and an outer one, mostly electrons, from about 13,000 km and densest near 15,000 to 25,000 km. The edges are fuzzy and move with the Sun." },
  { id: "t-saa", term: "South Atlantic Anomaly",
    text: "A region over South America and the South Atlantic where the magnetic field is weak, so the inner belt reaches down to low-orbit height. Spacecraft crossing it take more particle hits and more memory bit-flips." }
];
